# Generated by Django 5.1 on 2024-08-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users__panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
    ]
