# Generated by Django 5.1 on 2024-08-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users__panel', '0002_remove_data_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
