# Generated by Django 5.0.6 on 2024-08-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin__panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='bus',
            name='departure_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
    ]
