# Generated by Django 5.1 on 2024-08-12 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin__panel', '0005_remove_admin_email_admin_groups_admin_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reserved_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('reserved_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_seats', to='admin__panel.bus')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
